sudo: required

language: python

python:
  - "3.4"

services:
  - docker

cache:
  - apt
  
before_install:
  - docker build -t widukind/pysdmx .
 
-install:
  - pip install coveralls
 
before_script:
  - sleep 15
  - env
  - docker run --rm widukind/pysdmx freeze

script:
  - docker run --rm -v $PWD/coverage:/code/coverage widukind/pysdmx nosetests --with-coverage -s -v sdmx_tests
  - docker run --rm widukind/pysdmx flake8 --exit-zero
  
after_script: coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always
